[phases.setup]
nixPkgs = ['python310', 'gcc', 'glib', 'libGL']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'gunicorn --worker-class gevent -w 1 --timeout 120 --bind 0.0.0.0:$PORT app:app'